server.port: 8080
spring:
  application:
    name: jfcloud

# 配置输出日志
logging:
  config: classpath:logback-spring.xml
#  level:
#    root: debug
#    org.springframework.cloud.gateway: TRACE
#    org.springframework.http.server.reactive: DEBUG
#    org.springframework.web.reactive: DEBUG
#    reactor.ipc.netty: DEBUG

#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false